### ISSUE TITLE
gatling.outputName setting not working

### ISSUE THREAD

**Issue by tongqqiu** [gatling/gatling-maven-plugin#15]
When I execute the gatling test with ouputName

 ```mvn gatling:execute -Dgatling.simulationClass=test.class.name -Dgatling.outputName=xyz -X -debug```

I got the error

```
Error: Unknown option --on
Error: Unknown argument 'xyz'
Try --help for more information.
```
Debug shows the argument setting is correct. 

```[DEBUG]   (f) outputDirectoryBaseName = xyz```

I guess it is because somehow it passes "--on" instead "-on"

**Comment by slandelle** [comment]
Which version of gatling and of gatling-maven-plugin do you use?

**Comment by tongqqiu** [comment]
Gatling maven plugin is 2.0.0 which I think is the latest.

Gatling I tried 2.0.0 2.0.3 2.1.4 same issue

**Comment by slandelle** [comment]
No, the latest plugin is 2.1.2. Could you update please?

**Comment by tongqqiu** [comment]
That works great!
