### ISSUE TITLE
Does not find simulation files if run from parent directory

### ISSUE THREAD

**Issue by samion** [gatling/gatling-maven-plugin#18]
When I have a project structure Project/Test/Performance and the gatling pom.xml is under Performance directory and I run the tests from Project-level this way: Project$ mvn -f Test/Performance/pom.xml gatling:execute, I get the following error: 
[ERROR] Failed to execute goal io.gatling:gatling-maven-plugin:2.1.7:execute (default) on project Performance: Gatling failed. No simulations to run -> [Help 1]

It seems that the mvn command has to be run from the Performance directory, otherwise it will not find the tests. The above command worked with Gatling 2.0. This is usual problem when Gatling is run from Jenkins using the Maven build step which does not allow setting the working directory.

**Comment by slandelle** [comment]
Could you share a maven project sample, please?
We use the standard `basedir` maven var to resolve paths, so we should be fine.
Are you sure you don't have gatling maven plugin declared in the parent's build instead of just in the module that contains your simulations?

**Comment by slandelle** [comment]
Also, are you sure you don't override the directories, without using `${project.basedir}`?

**Comment by ulfherge** [comment]
+1 for this issue. Can not reproduce on windows (cywgin using maven 3.0.4 and 3.2.3) though, only on our linux build machines

**Comment by slandelle** [comment]
> Could you share a maven project sample, please?

@ulfherge Same question, same answer ;-)

**Comment by ulfherge** [comment]
The gatling plugin is in its own project containing only a gatling project.

oh the quick fix btw is the following in the configuration for the plugin:
<simulationClass>*</simulationClass>

**Comment by samion** [comment]
Here is an example project which exhibits this problem: https://github.com/samion/gatling-mvn-issue

**Comment by slandelle** [comment]
Fixed, see https://github.com/gatling/gatling/issues/2855

Thanks for the reproducer!
